### ISSUE TITLE
player's accountId

### ISSUE THREAD

**Issue by rafaelfgyn** [andshrew/PlayStation-Trophies#10]
hey andshrew,

congratulations for this amazing project.

I wonder if you know some route in the playstation api to get player's accountId of any player non related to the npsso key. For example, to get accountId of all player's friends.

**Comment by andshrew** [comment]
Hi @rafaelfgyn 

Thanks for your comment. I know of the following endpoints you can use. You should be able to authenticate to these in the same way which is mentioned [here](https://andshrew.github.io/PlayStation-Trophies/#/APIv2?id=querying-the-api).

---

`https://m.np.playstation.net/api/userProfile/v1/internal/users/me/friends`

This returns a list of the accountIds on the friends list of the account you used to authenticate with. You can also swap `me` for another accountId and you will get their friends list back (assuming the authenticating account has permission to view the other accounts friends list).

---

`https://m.np.playstation.net/api/userProfile/v1/internal/users/{accountId}/profiles`

This returns the basic profile details for an account so you can discover the onlineId (their PSN name) from an accountId.

---

`https://m.np.playstation.net/api/userProfile/v1/internal/users/me/friends/{accountId}/summary`

This gives you a relationship summary between the accountId and the authenticating account (are they a friend, a close friend, how many mutual friends you have etc).

---

It would be nice if there was a way to get the accountId and onlineId in a single request but I've not come across such an endpoint for doing that.

**Comment by rafaelfgyn** [comment]
man, thank you so much for all the hard work that you put in discovering some much about Sony's API. I'm about to launch a webpage so players can see their accounts, all thanks to your work, I have been work on this for about 2 years lol, so thank you again. 
That been said, I have to ask:
How did you manage to discovery so much about Sony' Api? How did you find the endpoints ,etc... I would like to help investigating the api, I believe there're more useful endpoints to be found.

**Comment by andshrew** [comment]
Hi @rafaelfgyn 

You're welcome, I'm glad it's been a useful resource for developing your web site.

Regarding discovery, as Sony have reduced the amount of services which are available via a regular web browser the majority of the current APIs come from inspecting the mobile PS App. You could discover a lot just by inspecting the files within the app package. They were originally visible in the plain text Javascript file (or at least visible enough that you could work out what they would be). You can still do this, but current versions of the app have these files compiled into Hermes bytecode so you have to disassemble it with a tool like https://github.com/bongtrop/hbctool. 

The other way is capturing and inspecting the traffic that the app is generating as you use it but that's not straight forward now due to the lengths developers go to try prevent this (eg. SSL certificate pinning), although it is still possible.

**Comment by rafaelfgyn** [comment]
I did manage to get the endpoints via regular web browser, after the launch of ps5 with the new api, they ended the old api and I lost all my job, it was a sad day to me (lol), now that everything turns around the mobile app, I'm lost. I know too little about mobile =/. I've tried to use some app the inspects the traffic but with no success.

**Comment by rafaelfgyn** [comment]
Hey man, do we have any endpoints to get the Id of a specific user?

**Comment by andshrew** [comment]
Hi @rafaelfgyn 

The closest thing I'm aware of which can effectively do a username to id lookup is their search API (so whether someone appears in this is going to depend on their privacy settings relative to the account you are using to perform the request).

The endpoint URL is: `https://m.np.playstation.com/api/search/v1/universalSearch`

You need to `POST` an `application/json` request with the following content:

```
{
  "searchTerm": "rafaelfgyn",
  "domainRequests": [
    {
      "domain": "SocialAllAccounts",
      "socialSearchParams": {
        "strictGrouping": true
      },
      "pagination": {
        "cursor": "",
        "pageSize": 20
      },
      "featureFlags": {
        "isSpartacusEnabled": true
      }
    }
  ],
  "countryCode": "gb",
  "languageCode": "en",
  "age": 99
}
```

You'll get a response like:
```
{
  "domainResponses": [
    {
      "domain": "SocialAllAccounts",
      "domainTitle": "Results for SocialAllAccounts with search term \"rafaelfgyn\"",
      "domainTitleMessageId": "msgid_null",
      "domainTitleHighlight": [
        "Results for SocialAllAccounts with search term \"",
        "rafaelfgyn",
        "\""
      ],
      "zeroState": false,
      "next": "",
      "totalResultCount": 1,
      "results": [
        {
          "id": "id",
          "type": "social",
          "score": 236.3765,
          "socialMetadata": {
            "accountId": "1234567890",
            "country": "BR",
            "language": "pt",
            "onlineId": "rafaelfgyn",
            "isPsPlus": false,
            "isOfficiallyVerified": false,
            "avatarUrl": "http://static-resource.np.community.playstation.net/avatar/3RD/UP00011308076_37E14E48D0E885B75F69_L.png",
            "verifiedUserName": "",
            "highlights": {
              "onlineId": [
                "",
                "rafaelfgyn"
              ]
            }
          }
        }
      ]
    }
  ],
  "fallbackQueried": false
}
```

You can use the same method of authentication as all of the trophy endpoints.

**Comment by Sakreetos** [comment]
Hello @andshrew,

I am getting this response using your example. I've tried to change username but no luck:

```
{
    "error": {
        "referenceId": "80d3d30c-5812-453f-81bf-135ee0279002",
        "code": 3415813,
        "message": "Friend finder requires a valid account",
        "reason": "invalid_parameter",
        "source": "api"
    }
}
```

**Comment by Sakreetos** [comment]
Yeah, already figured that out. Thank you)

**Comment by rafaelfgyn** [comment]
Man, thanks again for that. this endpoint is extremely useful. If you have any endpoints still to share please don't hesitate, or just update your documentation. If there's anything I can do to help just reach me out.

Changing of topic... did see this?
https://blog.playstation.com/2022/07/14/introducing-playstation-stars-an-all-new-loyalty-program/

**Comment by isFakeAccount** [comment]
You can use `https://us-prof.np.community.playstation.net/userProfile/v1/users/{online_id}/profile2?fields?accountId%2ConlineId%2CcurrentOnlineId` to get the account id from online id

**Comment by andshrew** [comment]
> You can use `https://us-prof.np.community.playstation.net/userProfile/v1/users/{online_id}/profile2?fields?accountId%2ConlineId%2CcurrentOnlineId` to get the account id from online id

That seems to work perfectly, but there's a small typo it should be fields= not fields?

`https://us-prof.np.community.playstation.net/userProfile/v1/users/{online_id}/profile2?fields=accountId%2ConlineId%2CcurrentOnlineId`

**Comment by isFakeAccount** [comment]
Yes, there is a typo. I messed up when copying from python to URL format.

**Comment by kamranayub** [comment]
I know this old, but just FYI for others searching, the `us-prof.np.community.playstation.net` endpoint is the best endpoint for getting `accountId` from an online ID as the universal search does not always find every PSN account by online ID I discovered. 😮

**Comment by isFakeAccount** [comment]
@kamranayub Yes. That is what I do in my api wrapper
