### ISSUE TITLE
Cannot index into a null array.

### ISSUE THREAD

**Issue by Sakreetos** [andshrew/PlayStation-Trophies#11]
Hello,

When I am trying to execute: 

`$token = Get-AuthenticationToken -npsso "Ghzhxl%%%%%%%%%%%%%%%%%%%%%%%%%%%"`

I am getting this kind of error:

```
Error: Check npsso
Cannot index into a null array.
At C:\Users\o.sikorskyi\OneDrive - Playtech\Desktop\test.ps1:22 char:1
+ $body = @{
+ ~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

What kind of issue is this?

**Comment by andshrew** [comment]
Hi @Sakreetos

Can you check what version of Powershell you are using by typing $PSVersionTable.

I've only tested it with version 7, but it does not work with version 5 (the version included with Windows 10).

You can download version 7 here: https://github.com/PowerShell/PowerShell#get-powershell

**Comment by Sakreetos** [comment]
@andshrew thank you. It is working now.
