### ISSUE TITLE
Endpoint limit parameter values

### ISSUE THREAD

**Issue by aron0306** [andshrew/PlayStation-Trophies#14]
First of all, thank you so much for all your work on this project, it is really something unique!

I'm doing some tests with the api (using isFakeAccount Python wrapper) and found out that the limit parameter values for the endpoint https://m.np.playstation.net/api/trophy/v1/users/{accountId}/trophyTitles are as follows:

Min 1 (already in the documentation)
Max 800 (higher values will return an 400 bad request http error)
Default 100 (if not specified it will limit to 100 game titles trophies)

Since the numbers os trophies and titles are very different in sizes I believe the values may be different on other endpoints, but I'll try to confirm it and let you know.

Since I'm not a developer and have little to no experience with Git commands etc I'm posting it here. 😅

**Comment by andshrew** [comment]
Hi @aron0306 

Thanks for this, I'll update the documentation with your findings.

**Comment by andshrew** [comment]
These limits have been updated now.
