### ISSUE TITLE
Current (PS5 / "v2") Base URL may have changed from .net to .com

### ISSUE THREAD

**Issue by andshrew** [andshrew/PlayStation-Trophies#15]
The base URL for accessing the API was `https://m.np.playstation.net/api/trophy`

It appears this may now be `https://m.np.playstation.com/api/trophy`

**Comment by Avalanchee** [comment]
Legend!
I've been seeing errors all day so definitely felt like something broke.. only hoped it wasn't a serious issue.

Much appreciated :)

**Comment by gamerxsocietydev** [comment]
@andshrew @Avalanchee Do we have confirmation on if the API is back up and accessible? I am still receiving errors

**Comment by jeroenbourgois** [comment]
@andshrew ABSOLUTE LEGEND!!!!!

**Comment by andshrew** [comment]
Documentation updated:
https://github.com/andshrew/PlayStation-Trophies/commit/fc7a13d34646e16873baba0defbb2d50b4f2d620
