### ISSUE TITLE
Would there be interest in a Postman collection with the endpoints and tests?

### ISSUE THREAD

**Issue by TheYuriG** [andshrew/PlayStation-Trophies#17]
I'm making a public Postman collection that hits the endpoints, authenticates, and then requests for data, in a practical way, akin to what your documentation library refers to.

[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/14106843-e19286eb-8d3d-4fcf-97eb-abbe368462b5?action=collection%2Ffork&collection-url=entityId%3D14106843-e19286eb-8d3d-4fcf-97eb-abbe368462b5%26entityType%3Dcollection%26workspaceId%3D74248cb6-445a-40c0-a1b3-e2f39a55bced)

Would you be interested in having this added to your documentation, so your users can easily test the endpoints you describe? The greatest advantages of integrating the documentation with Postman are:
- Very easy testing of endpoints;
- Straightforward testing samples of expected outputs for each endpoint;
- The ability to easily convert requests to code in any popular language;

PS: Thanks for the library, I'm doing my best to not fanboy too much. 😅

**Comment by andshrew** [comment]
Hi @TheYuriG 

I'm glad you've found this useful, and thanks for your suggestion. 

I certainly like the idea of it. The only reservation I have around linking to it would be a concern around the authentication side of it and wanting to make sure that a users SSO token couldn't potentially be stolen by - for example - the Postman collection being altered at a later time to add in an extra step/endpoint which sends that information off to a malicious web server.

Do you know if is it possible to link to a specific version of the collection, or will it always link to the latest version? If it were possible to link to a specific version that could potentially mitigate this concern.

I don't know if my concern is even possible (and I'm also not wanting to suggest you would do such a thing if it is!), but for as convenient as this could be for allowing someone to access the API when handling/automating the authentication for the user I'd want to make sure there's no risk of someone compromising the security of their PSN account by using it.

**Comment by TheYuriG** [comment]
> Do you know if is it possible to link to a specific version of the collection, or will it always link to the latest version?

I'll look into it and let you know!

> I don't know if my concern is even possible (and I'm also not wanting to suggest you would do such a thing if it is!), but for as convenient as this could be for allowing someone to access the API when handling/automating the authentication for the user I'd want to make sure there's no risk of someone compromising the security of their PSN account by using it.

Yeah, I understand the concern, there are tons of ways it could go bad like my account getting compromised and the Collection stolen, etc. I'll keep building for myself for now (since I actually really need this to test the endpoints anyway) and I'll get back to you in a few days about how we can safely share this.

**Comment by andshrew** [comment]
Thanks, I look forward to seeing what you come up with.

**Comment by TheYuriG** [comment]
All the current endpoints are there, but I'm unable to test any of the old endpoints (the V1 ones with `.net`).

Are you still able to connect to those just fine?

Dunno if I'm doing something wrong or all these legacy V1 endpoints died [when this happened](https://github.com/achievements-app/psn-api/issues/97#issuecomment-1282978082) because all I get are `403 FORBIDDEN`s.
