### ISSUE TITLE
played time for a game

### ISSUE THREAD

**Issue by rafaelfgyn** [andshrew/PlayStation-Trophies#19]
Hello, I would like to know if there's a route to get users played time in a specific game.

Some webpages like exophase already have this feature.

Thanks!

**Comment by andshrew** [comment]
Yep, there is. Have a look at https://github.com/andshrew/PlayStation-Trophies/issues/12

**Comment by rafaelfgyn** [comment]
Weird, I have tried this endpoint `https://m.np.playstation.net/api/gamelist/v2/users/me/titles`, but doesn't seem to work at all. I did authenticate and all but can't even get a return from the API.

**Comment by andshrew** [comment]
Ah, they discontinued use of playstation.net at some point after that post and only use playstation.com now. It should work if you use:

`https://m.np.playstation.com/api/gamelist/v2/users/me/titles`

**Comment by rafaelfgyn** [comment]
Worked, thanks a lot!
