### ISSUE TITLE
Game Region Data

### ISSUE THREAD

**Issue by rafaelfgyn** [andshrew/PlayStation-Trophies#20]
Hello, I would like to know if there's a way of getting the region of a game through Sony's API. For example. One game can have multiple instances by region, ASIA, USA, EU, etc...

**Comment by andshrew** [comment]
Hi @rafaelfgyn 

I don't know of a direct way of finding this information.

You could indirectly figure this out using [the Title Id trophy endpoint](https://andshrew.github.io/PlayStation-Trophies/#/APIv2?id=trophy-title-summary-for-specific-title-id) if you had a list of known Title Ids to run against it (hint: [PlayStation-Titles](https://github.com/andshrew/PlayStation-Titles)).

But you'll run into the same limitation that all of the trophy endpoints have; you only get information back from the API if the account you are querying against has played the game.
