### ISSUE TITLE
GamesList route unavailable

### ISSUE THREAD

**Issue by rafaelfgyn** [andshrew/PlayStation-Trophies#29]
[https://m.np.playstation.com/api/gamelist/v2/users/{id}/titles?limit=20&offset=0](https://m.np.playstation.com/api/gamelist/v2/users/%7Bid%7D/titles?limit=20&offset=0)

The given service is returning 503 for the past 2/3 days.

This route should return, among other things, the playDuration for a user's game.

Someone is aware of that?

**Comment by andshrew** [comment]
I'm not seeing that issue.

Have you tried different network troubleshooting like using a different DNS server?

**Comment by rafaelfgyn** [comment]
Really? That's weird. I'm reaching the API actually. I'm getting this.

**Comment by rafaelfgyn** [comment]
Really? That's weird. I'm reaching the API actually. I'm getting this.
```

{
    "error": {
        "reason": "ServiceUnavailable",
        "source": "Gamelist",
        "code": 3239938,
        "message": "Service Unavailable at Auth",
        "referenceId": "b0caa9fb-8ae6-1031-ad77-877297fc3296"
    }
}
```

**Comment by andshrew** [comment]
Interesting. If you try to access it without any credentials do you get the no credentials supplied message, or do you get the same service unavailable error?
```
{
    "error": {
        "reason": "MissingAuthCredentials",
        "code": 3239954,
        "source": "Gamelist",
        "message": "No credentials supplied",
        "referenceId": "178277cf-8ab2-1031-a267-913c3579bfd6"
    }
}
```

**Comment by rafaelfgyn** [comment]
Well... this route was off september 5th but turned back in a couple of hours, I've just saw the token had expired and it was returning exactly the same 503 payload. 

It's working now. Sorry for the misundertanding and thanks again for the support.
