### ISSUE TITLE
Problem with the Get-AuthenticationToken method

### ISSUE THREAD

**Issue by rafaelfgyn** [andshrew/PlayStation-Trophies#3]
First, congratulations for the amazing work on this project, very impressive indeed.

I'm having some trouble when I try to use the Get-AuthenticationToken method with my npsso string.
it throws me the following error message:

![image](https://user-images.githubusercontent.com/64870651/120378737-2ea0d380-c2f5-11eb-836c-ee938e8b3d2b.png)

Do you know what could possibly be the solution for this?

**Comment by andshrew** [comment]
Hi @rafaelfgyn - thanks for that.

Are you using Powershell 7? You can check by running `$PSVersionTable`. If you don't have it you can download it from https://github.com/PowerShell/PowerShell#get-powershell 

It has a few enhancements over Powershell 5.1 - which is included with Windows 10 - especially when it comes to making web requests with `Invoke-WebRequest` and `Invoke-RestMethod`. All of the examples here and the `Get-AuthenticationToken` method depend on these new features and I think this is what is causing your error.

Andrew

**Comment by rafaelfgyn** [comment]
Yeah, It was that what happen. Problem solved. Thanks a lot!
