### ISSUE TITLE
Docs are offline

### ISSUE THREAD

**Issue by rafaelfgyn** [andshrew/PlayStation-Trophies#30]
It seems the documation if offline for a few days.

will It be back?

https://andshrew.github.io/PlayStation-Trophies/#/APIv2?id=powershell-7

**Comment by Ragowit** [comment]
Must have been a hiccup or something, the site is working just fine for me.

**Comment by andshrew** [comment]
Is it still not working for you @rafaelfgyn ?

If it isn't, I'm not sure what else I can do as the site is automagically hosted by GitHub Pages. Other than suggest the usual troubleshooting, eg. try a different DNS server, try your browser in private mode.

**Comment by rafaelfgyn** [comment]
@andshrew , I am accessing now, but only by notebook. My desktop is not accessing. Odd

**Comment by Ragowit** [comment]
Something odd with your desktop then. Does it work with another browser?

**Comment by rafaelfgyn** [comment]
all browsers with the issue. But don't matter, I'm able to access by notebook, It won't be much of a problem then.

**Comment by andshrew** [comment]
@rafaelfgyn I'm going to close this now since the issue seems to be something specific to your computer.

**Comment by rafaelfgyn** [comment]
No worries, thanks!
